[build]
  publish = "dist"
  command = "npm run build"

[context.production]
  branch = "prod"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  context = "main"
  command = "npm run build"
  publish = "dist"