name: Code checks

on:
  pull_request:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [checks, build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rebase to target branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin
          git rebase origin/${{ github.event.pull_request.base.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.job }}
        run: npm run ${{ matrix.job }}
